apiVersion: skaffold/v1beta4
kind: Config
metadata:
  name: my-todo-cluster-dev

build:
  tagPolicy:
    sha256: {}      # Utilisez `sha256` pour générer des tags uniques (remplace `gitCommit` pour v0.25.0).
  local:
    push: true      # Pousse les images vers un registre distant.

manifests:
  rawYaml:
    - ./k8s/deploy/deploy-to-cluster-dev.yaml
    - ./k8s/*
