apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: my-todo-app-pipeline
  labels:
    app: cicd
description: cicd delivery pipeline
serialPipeline:
  stages:
  - targetId: my-todo-app-pipeline-target-1
    # profiles:
    # - dev
  # - targetId: staging
  #   profiles:
  #   - staging
  # - targetId: prod
  #   profiles:
  #   - prod