apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-nodejs-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-todo-app-backend
  template:
    metadata:
      labels:
        app: my-todo-app-backend
  spec:
    containers:
      - name: my-todo-app-backend
        image: africa-south1-docker.pkg.dev/my-todo-app-project-445006/my-todo-app-repo/my-todo-app-backend
        ports:
          - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: my-todo-app-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer