apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-react-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-todo-app-frontend
  template:
    metadata:
      labels:
        app: my-todo-app-frontend
  spec:
    containers:
      - name: my-todo-app-frontend
        image: africa-south1-docker.pkg.dev/my-todo-app-project-445006/my-todo-app-repo/my-todo-app-frontend
        ports:
          - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: my-todo-app-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer