name: CI/CD Pipeline

on:
  push:
    # branches:
      # - main
  pull_request:
    # branches:
      # - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

        # Étape 1 : Build et push de l'image Docker pour le backend
      - name: Build and Push Backend Docker Image
        run: |
          docker build -t my-dockerhub-username/todo-backend:${{ github.sha }} ./backend
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push my-dockerhub-username/todo-backend:${{ github.sha }}

        # Étape 2 : Build et push de l'image Docker pour le frontend
      - name: Build and Push Frontend Docker Image
        run: |
          docker build -t my-dockerhub-username/todo-frontend:${{ github.sha }} ./frontend
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push my-dockerhub-username/todo-frontend:${{ github.sha }}

        # Étape 3 : Push vers AWS ECR
      - name: Push Docker images to AWS ECR
        run: |
          aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 123456789012.dkr.ecr.us-west-2.amazonaws.com
          docker tag my-dockerhub-username/todo-backend:${{ github.sha }} 123456789012.dkr.ecr.us-west-2.amazonaws.com/todo-backend:${{ github.sha }}
          docker tag my-dockerhub-username/todo-frontend:${{ github.sha }} 123456789012.dkr.ecr.us-west-2.amazonaws.com/todo-frontend:${{ github.sha }}
          docker push 123456789012.dkr.ecr.us-west-2.amazonaws.com/todo-backend:${{ github.sha }}
          docker push 123456789012.dkr.ecr.us-west-2.amazonaws.com/todo-frontend:${{ github.sha }}

        # Étape 4 : Déploiement sur Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/todo-backend todo-backend=123456789012.dkr.ecr.us-west-2.amazonaws.com/todo-backend:${{ github.sha }}
          kubectl set image deployment/todo-frontend todo-frontend=123456789012.dkr.ecr.us-west-2.amazonaws.com/todo-frontend:${{ github.sha }}
          kubectl rollout restart deployment/todo-backend
          kubectl rollout restart deployment/todo-frontend

        # Étape 5 : Exécution des tests
      - name: Run Unit Tests with Jest
        run: |
          docker run --rm my-dockerhub-username/todo-backend:${{ github.sha }} npm test

      - name: Run Integration Tests with Cypress
        run: |
          docker run --rm my-dockerhub-username/todo-backend:${{ github.sha }} npm run test:integration
